[project]
name = "cabal-ai"
version = "0.1.0"
description = "Your AI Team right on your Slack. Open-source and forkable."
readme = "README.md"
authors = [
    { name = "Cosmin Tudor", email = "cosmin2dor@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "sqlmodel>=0.0.38",
]

[project.scripts]
cabal = "cabal_ai:main"
db = "core.db:init_db"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
